# @name getPrompts
GET http://localhost:3333/prompts
###

# @name uploadVideo
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="music.mp3"
Content-Type: audio/mpeg

< ./music.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# @name create-transcription
POST http://localhost:3333/videos/8f4e8f90-0355-4bca-a10c-432cab02db40/transcription
Content-Type: application/json

{
  "prompt": "Music Brazilian Hype"
}
###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "8f4e8f90-0355-4bca-a10c-432cab02db40",
  "temperature": 0.5,
  "template": "gere um resumo do vídeo video: '''{transcription}'''"
}